name: Terraform CI

on:
  push:
    branches:
      - main
      - v2-refactor

  pull_request:
    branches:
      - main

  permissions:
    id-token: write
    contents: read

jobs:
  terraform:
    name: Terraform Validation
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::604582501995:role/multi-tier-github-actions-role
          aws-region: ap-south-1

    

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      
      - name: Terraform Plan
        run: terraform plan -input=false 